name: flutter_draggable_linux_sample
description: "drag and drop sample for linux"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  path:

  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  riverpod_lint: ^2.3.10
  custom_lint: ^0.6.2
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/